import type { CompositionTemplate } from "../types";

/** Plantilla oficial Clickatón — Story 1080×1920 */
export const CLICKATON_WELCOME_STORY_V1: CompositionTemplate = {
  id: "clickaton.welcome.story",
  name: "Clickatón — Bienvenida Story",
  version: 1,
  platform: "CLICKATON",
  kind: "WELCOME_STORY",
  width: 1080,
  height: 1920,
  background: "#0a0a0a",
  variables: [
    "participantName",
    "instagram",
    "participantNumber",
    "city",
    "province",
    "editionName",
    "editionDate",
  ],
  blocks: [
    {
      id: "accent-top",
      type: "rect",
      x: 0,
      y: 0,
      width: 1080,
      height: 12,
      fill: "#f5c518",
    },
    {
      id: "logo",
      type: "image",
      x: 340,
      y: 120,
      width: 400,
      height: 160,
      assetKey: "logo",
      fit: "contain",
      shape: "rect",
    },
    {
      id: "welcome",
      type: "text",
      x: 80,
      y: 320,
      width: 920,
      fontSize: 42,
      fontWeight: "bold",
      color: "#f5c518",
      align: "center",
      content: "¡Bienvenido a Clickatón!",
    },
    {
      id: "photo",
      type: "image",
      x: 240,
      y: 420,
      width: 600,
      height: 600,
      assetKey: "photo",
      fit: "cover",
      shape: "circle",
      borderColor: "#f5c518",
      borderWidth: 10,
    },
    {
      id: "name",
      type: "text",
      x: 80,
      y: 1080,
      width: 920,
      fontSize: 56,
      fontWeight: "bold",
      color: "#fafafa",
      align: "center",
      content: "{{participantName}}",
      maxLines: 2,
    },
    {
      id: "instagram",
      type: "text",
      x: 80,
      y: 1180,
      width: 920,
      fontSize: 36,
      color: "#a1a1a1",
      align: "center",
      content: "@{{instagram}}",
    },
    {
      id: "number",
      type: "text",
      x: 80,
      y: 1280,
      width: 920,
      fontSize: 48,
      fontWeight: "bold",
      color: "#f5c518",
      align: "center",
      content: "{{participantNumber}}",
    },
    {
      id: "city",
      type: "text",
      x: 80,
      y: 1380,
      width: 920,
      fontSize: 32,
      color: "#d4d4d4",
      align: "center",
      content: "{{city}}",
    },
    {
      id: "edition",
      type: "text",
      x: 80,
      y: 1680,
      width: 920,
      fontSize: 28,
      color: "#737373",
      align: "center",
      content: "{{editionName}} · {{editionDate}}",
    },
    {
      id: "accent-bottom",
      type: "rect",
      x: 0,
      y: 1908,
      width: 1080,
      height: 12,
      fill: "#f5c518",
    },
  ],
};
