import type { CompositionTemplate } from "../types";

/**
 * Plantilla versionable de credencial Clickatón (preview).
 * No genera credenciales productivas automáticamente — requiere diseño aprobado.
 * Separada de la placa de bienvenida (`clickaton.welcome.story`).
 */
export const CLICKATON_CREDENTIAL_PREVIEW_V1: CompositionTemplate = {
  id: "clickaton.credential.preview",
  name: "Clickatón — Credencial preview",
  version: 1,
  platform: "CLICKATON",
  kind: "CUSTOM",
  width: 1080,
  height: 1600,
  background: "#0a0a0a",
  variables: [
    "participantName",
    "participantNumber",
    "city",
    "editionName",
    "roleLabel",
  ],
  blocks: [
    {
      id: "accent-top",
      type: "rect",
      x: 0,
      y: 0,
      width: 1080,
      height: 16,
      fill: "#f5c518",
    },
    {
      id: "logo",
      type: "image",
      x: 340,
      y: 80,
      width: 400,
      height: 140,
      assetKey: "logo",
      fit: "contain",
      shape: "rect",
    },
    {
      id: "role",
      type: "text",
      x: 80,
      y: 260,
      width: 920,
      fontSize: 28,
      fontWeight: "bold",
      color: "#f5c518",
      align: "center",
      content: "{{roleLabel}}",
    },
    {
      id: "photo",
      type: "image",
      x: 315,
      y: 320,
      width: 450,
      height: 450,
      assetKey: "photo",
      fit: "cover",
      shape: "circle",
      borderColor: "#f5c518",
      borderWidth: 8,
    },
    {
      id: "name",
      type: "text",
      x: 80,
      y: 820,
      width: 920,
      fontSize: 48,
      fontWeight: "bold",
      color: "#fafafa",
      align: "center",
      content: "{{participantName}}",
      maxLines: 2,
    },
    {
      id: "number",
      type: "text",
      x: 80,
      y: 920,
      width: 920,
      fontSize: 56,
      fontWeight: "bold",
      color: "#f5c518",
      align: "center",
      content: "{{participantNumber}}",
    },
    {
      id: "qr-placeholder",
      type: "rect",
      x: 340,
      y: 1040,
      width: 400,
      height: 400,
      fill: "#141414",
    },
    {
      id: "qr-hint",
      type: "text",
      x: 80,
      y: 1460,
      width: 920,
      fontSize: 24,
      color: "#737373",
      align: "center",
      content: "QR · {{city}} · {{editionName}}",
    },
  ],
};
