import type { TemplateVariableDefinition } from "../../variables/types";

/**
 * Variables de FotoOffice: lo que una institución puede poner en una credencial, una placa o
 * una historia de bienvenida.
 *
 * Este archivo es la **única** fuente. Antes había dos listas: una que el editor mostraba y
 * otra que el motor validaba y renderizaba. FotoOffice existía solo en la primera, así que se
 * podía poner la foto del socio en el diseño y la vista previa la rechazaba como variable
 * desconocida. El catálogo del editor ahora se deriva de acá.
 *
 * Las claves coinciden con las que entrega `apps/fotoffice/lib/carnet/render.ts` al emitir. No
 * es prolijidad: si difirieran haría falta una capa de traducción, y esa capa sería un lugar
 * más donde una variable queda en blanco sin que nadie lo note.
 */
export const FOTOFFICE_TEMPLATE_VARIABLE_DEFINITIONS: TemplateVariableDefinition[] = [
  // ── Socio ──
  {
    path: "fullName",
    label: "Socio - Nombre y apellido",
    description: "Nombre completo, como figura en el padrón.",
    valueType: "text",
    required: true,
    example: "María Fernanda Gómez",
    aliases: ["socio", "nombredelsocio", "nombrecompleto"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "firstName",
    label: "Socio - Nombre",
    description: "Solo el nombre. Útil para un saludo.",
    valueType: "text",
    example: "María Fernanda",
    formatters: ["none", "uppercase", "titleCase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "lastName",
    label: "Socio - Apellido",
    valueType: "text",
    example: "Gómez",
    formatters: ["none", "uppercase", "titleCase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "memberNumber",
    label: "Socio - Número",
    description: "El número que identifica al socio en el padrón.",
    valueType: "text",
    required: true,
    example: "428",
    aliases: ["numerodesocio", "nrosocio"],
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "category",
    label: "Socio - Categoría",
    description: "Profesional, Estudiante, Honorario… según la institución.",
    valueType: "text",
    example: "Profesional",
    formatters: ["none", "uppercase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "documentNumber",
    label: "Socio - Documento",
    description: "Número de documento. Puede estar vacío en el padrón.",
    valueType: "text",
    example: "28.114.507",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "joinedAt",
    label: "Socio - Socio desde",
    description: "Fecha de alta. Sirve para mostrar antigüedad.",
    valueType: "date",
    example: "2014-03-15",
    formatters: ["date.short", "date.long", "date.longUppercase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "photo",
    label: "Socio - Foto",
    description: "La foto que el socio subió desde su portal.",
    valueType: "image",
    required: true,
    example: "socios/ejemplo/foto.png",
    aliases: ["fotodelsocio", "fotocarnet"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "email",
    label: "Socio - Email",
    valueType: "text",
    example: "socio@example.com",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "phone",
    label: "Socio - Teléfono",
    valueType: "text",
    example: "+54 341 555-0142",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },
  {
    path: "city",
    label: "Socio - Ciudad",
    valueType: "text",
    example: "Rosario",
    formatters: ["none", "uppercase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "socio",
    groupLabel: "Socio",
  },

  // ── Credencial ──
  {
    path: "cardNumber",
    label: "Credencial - Número",
    description: "Identifica a esta credencial, no al socio: si se reemite, cambia.",
    valueType: "text",
    required: true,
    example: "SFPR-2026-000428",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "credencial",
    groupLabel: "Credencial",
  },
  {
    path: "validUntil",
    label: "Credencial - Vigente hasta",
    description: "Hasta cuándo vale esta credencial.",
    valueType: "date",
    required: true,
    example: "2027-12-31",
    formatters: ["date.short", "date.long"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "credencial",
    groupLabel: "Credencial",
  },
  {
    path: "verificationUrl",
    label: "Credencial - URL de verificación",
    description:
      "La dirección que confirma si el socio está habilitado. Es lo que va en el QR: cambia con cada credencial, así que verifica a esa persona y no a otra.",
    valueType: "qrUrl",
    required: true,
    example: "https://fotoffice.com/c/AB12CD34EF56GH78",
    aliases: ["qr", "verificador"],
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "credencial",
    groupLabel: "Credencial",
  },

  // ── Institución ──
  {
    path: "institutionName",
    label: "Institución - Nombre",
    description: "El nombre comercial de la institución, o el del workspace si no tiene uno.",
    valueType: "text",
    required: true,
    example: "Sociedad de Fotógrafos Profesionales de Rosario",
    aliases: ["institucion", "sociedad"],
    formatters: ["none", "uppercase"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "institucion",
    groupLabel: "Institución",
  },
  {
    path: "institutionLogo",
    label: "Institución - Logo",
    description: "El logo cargado en la configuración de la institución.",
    valueType: "image",
    example: "instituciones/ejemplo/logo.png",
    aliases: ["logoinstitucion", "logo"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "institucion",
    groupLabel: "Institución",
  },
];
