/**
 * Catálogo de iconos - mapeo semántico a lucide-react.
 * Usar solo estos nombres en toda la suite.
 */

import {
  LogIn,
  LogOut,
  UserPlus,
  KeyRound,
  User,
  UserCog,
  Settings,
  Bell,
  Shield,
  Menu,
  PanelLeftClose,
  Home,
  LayoutDashboard,
  ArrowLeft,
  ArrowRight,
  ChevronDown,
  ChevronUp,
  MoreHorizontal,
  ChevronRight,
  ArrowUpToLine,
  SlidersHorizontal,
  Globe,
  Sun,
  Moon,
  Lock,
  Loader2,
  CircleCheck,
  CircleX,
  TriangleAlert,
  Info,
  ImageOff,
  WifiOff,
  RefreshCw,
  Camera,
  Images,
  Album,
  Upload,
  Download,
  Image,
  Heart,
  Eye,
  EyeOff,
  MousePointerClick,
  Printer,
  ShoppingBag,
  ShoppingCart,
  CreditCard,
  Wallet,
  Receipt,
  FileText,
  QrCode,
  ArrowLeftRight,
  TicketPercent,
  Tag,
  Percent,
  Share2,
  Link,
  Send,
  MessageCircle,
  Mail,
  Save,
  Copy,
  Archive,
  ArchiveRestore,
  Trash2,
  CircleSlash,
  Pencil,
  Plus,
  Calendar,
  Clock,
  CalendarDays,
  Search,
  Filter,
  ArrowUpDown,
  X,
} from "lucide-react";

export const iconMap = {
  login: LogIn,
  logout: LogOut,
  register: UserPlus,
  changePassword: KeyRound,
  user: User,
  userEdit: UserCog,
  userSettings: UserCog,
  notifications: Bell,
  security: Shield,
  menu: Menu,
  sidebarToggle: PanelLeftClose,
  home: Home,
  dashboard: LayoutDashboard,
  arrowBack: ArrowLeft,
  arrowForward: ArrowRight,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
  more: MoreHorizontal,
  breadcrumb: ChevronRight,
  scrollTop: ArrowUpToLine,
  settings: Settings,
  preferences: SlidersHorizontal,
  language: Globe,
  theme: Sun,
  privacy: Lock,
  permissions: Shield,
  loading: Loader2,
  success: CircleCheck,
  error: CircleX,
  warning: TriangleAlert,
  info: Info,
  empty: ImageOff,
  offline: WifiOff,
  sync: RefreshCw,
  camera: Camera,
  gallery: Images,
  album: Album,
  upload: Upload,
  download: Download,
  image: Image,
  favorite: Heart,
  eye: Eye,
  hide: EyeOff,
  select: MousePointerClick,
  print: Printer,
  buy: ShoppingBag,
  cart: ShoppingCart,
  creditCard: CreditCard,
  payment: Wallet,
  receipt: Receipt,
  invoice: FileText,
  qr: QrCode,
  transfer: ArrowLeftRight,
  discount: TicketPercent,
  coupon: Tag,
  commission: Percent,
  share: Share2,
  copyLink: Link,
  send: Send,
  message: MessageCircle,
  email: Mail,
  whatsapp: MessageCircle,
  facebook: MessageCircle,
  instagram: Image,
  twitter: Send,
  tiktok: Send,
  save: Save,
  saveAll: Save,
  duplicate: Copy,
  copy: Copy,
  move: ArrowLeftRight,
  archive: Archive,
  restore: ArchiveRestore,
  delete: Trash2,
  disable: CircleSlash,
  enable: CircleCheck,
  edit: Pencil,
  plus: Plus,
  calendar: Calendar,
  clock: Clock,
  reminder: Bell,
  event: CalendarDays,
  search: Search,
  filter: Filter,
  sort: ArrowUpDown,
  close: X,
  clearFilters: X,
} as const;

export type IconName = keyof typeof iconMap;
