import type { TemplateVariableDefinition } from "../../variables/types";

/**
 * Definiciones escolares (solo catálogo).
 * Sin Prisma, pedidos ni resolución de negocio — el caller entrega `data`.
 */
export const SCHOOL_TEMPLATE_VARIABLE_DEFINITIONS: TemplateVariableDefinition[] = [
  {
    path: "student.fullName",
    label: "Alumno - Nombre completo",
    description: "Nombre y apellido del alumno.",
    valueType: "text",
    required: true,
    example: "María Gómez",
    aliases: ["alumno", "nombredelalumno", "nombrecompleto", "apellido"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "student",
    groupLabel: "Alumno",
  },
  {
    path: "buyer.fullName",
    label: "Cliente - Nombre completo",
    description: "Nombre del comprador o adulto responsable.",
    valueType: "text",
    required: true,
    example: "Ana Rodríguez",
    aliases: ["cliente", "comprador"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "buyer",
    groupLabel: "Cliente",
  },
  {
    path: "school.name",
    label: "Escuela - Nombre",
    description: "Nombre de la institución escolar.",
    valueType: "text",
    required: true,
    example: "Escuela Ejemplo",
    aliases: ["escuela", "colegio"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "school",
    groupLabel: "Escuela",
  },
  {
    path: "course.displayName",
    label: "Curso - Nombre visible",
    description: "Nombre de curso y división listo para imprimir.",
    valueType: "text",
    required: true,
    example: "3.º B · Mañana",
    aliases: ["curso", "division"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "course",
    groupLabel: "Curso",
  },
  {
    path: "order.referenceShort",
    label: "Pedido - Referencia corta",
    description: "Referencia corta de seguimiento del pedido/ítem.",
    valueType: "text",
    required: true,
    example: "P-1024",
    aliases: ["pedido", "referencia"],
    formatters: ["none", "uppercase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "order",
    groupLabel: "Pedido",
  },
  {
    path: "order.fulfillmentQrUrl",
    label: "Pedido - URL QR de entrega",
    description: "URL final codificada en el QR de entrega.",
    valueType: "qrUrl",
    required: true,
    example: "https://ejemplo.com/escolar/entrega/preview",
    aliases: ["qr"],
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "order",
    groupLabel: "Pedido",
  },
  {
    path: "photographer.displayName",
    label: "Fotógrafo - Nombre público",
    description: "Nombre de marca o nombre público del fotógrafo.",
    valueType: "text",
    required: true,
    example: "Estudio Fotográfico",
    aliases: ["fotografo"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "photographer",
    groupLabel: "Fotógrafo",
  },
  {
    path: "event.dateFormatted",
    label: "Evento - Fecha formateada",
    description: "Fecha del evento en formato corto para impresión.",
    valueType: "date",
    required: true,
    example: "17/04/2026",
    aliases: ["anio", "ano", "fecha"],
    formatters: ["none", "date.short"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "event",
    groupLabel: "Evento",
  },
  {
    path: "branding.schoolLogoUrl",
    label: "Marca - Logo escuela",
    description: "Logo institucional de la escuela (PNG transparente preferido).",
    valueType: "image",
    required: true,
    example: "https://cdn.example.com/school-logo.png",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "branding",
    groupLabel: "Marca",
  },
  {
    path: "branding.photographerLogoUrl",
    label: "Marca - Logo fotógrafo",
    description: "Logo del estudio/fotógrafo.",
    valueType: "image",
    required: true,
    example: "https://cdn.example.com/photographer-logo.png",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "branding",
    groupLabel: "Marca",
  },
];
