-- Nuevos tipos de evento (sesiones públicas/privadas, escolares, religiosos, etc.)
ALTER TYPE "EventType" ADD VALUE 'PUBLIC_SESSION';
ALTER TYPE "EventType" ADD VALUE 'PRIVATE_SESSION';
ALTER TYPE "EventType" ADD VALUE 'PUBLIC_PHOTOGRAPHY';
ALTER TYPE "EventType" ADD VALUE 'THEMATIC_SESSIONS';
ALTER TYPE "EventType" ADD VALUE 'COMMERCIAL_SESSIONS';
ALTER TYPE "EventType" ADD VALUE 'SCHOOL';
ALTER TYPE "EventType" ADD VALUE 'RELIGIOUS';
ALTER TYPE "EventType" ADD VALUE 'FESTIVAL';
ALTER TYPE "EventType" ADD VALUE 'CONFERENCE';
