import type { TemplateVariableDefinition } from "../../variables/types";

const TEXT_FMT = ["none", "uppercase", "titleCase", "truncate"] as const;
const DATE_FMT = [
  "none",
  "date.short",
  "date.long",
  "date.longUppercase",
  "date.dayMonthUppercase",
] as const;

/**
 * Catálogo Clickatón — independiente del plugin escolar.
 */
export const CLICKATON_TEMPLATE_VARIABLE_DEFINITIONS: TemplateVariableDefinition[] = [
  // —— Participante ——
  {
    path: "participant.id",
    label: "Participante - ID",
    valueType: "text",
    example: "p-demo-001",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.fullName",
    label: "Participante - Nombre completo",
    valueType: "text",
    required: true,
    example: "Daniel Fotógrafo",
    aliases: ["participante", "nombre", "nombrecompleto"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.firstName",
    label: "Participante - Nombre",
    valueType: "text",
    example: "Daniel",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.lastName",
    label: "Participante - Apellido",
    valueType: "text",
    example: "Fotógrafo",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.displayName",
    label: "Participante - Nombre display",
    valueType: "text",
    example: "DANIEL FOTÓGRAFO",
    formatters: [...TEXT_FMT, "uppercase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.instagram",
    label: "Participante - Instagram (sin @)",
    valueType: "text",
    example: "dnxfotografia",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.instagramHandle",
    label: "Participante - Instagram (@)",
    valueType: "text",
    example: "@dnxfotografia",
    aliases: ["instagram", "ig"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.city",
    label: "Participante - Ciudad",
    valueType: "text",
    example: "Rosario",
    aliases: ["ciudad"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.province",
    label: "Participante - Provincia",
    valueType: "text",
    example: "Santa Fe",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.country",
    label: "Participante - País",
    valueType: "text",
    example: "Argentina",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.category",
    label: "Participante - Categoría",
    valueType: "text",
    example: "Profesional",
    aliases: ["categoria"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.number",
    label: "Participante - Número",
    valueType: "number",
    example: 154,
    formatters: ["none", "participantNumber"],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.numberFormatted",
    label: "Participante - Número formateado",
    valueType: "text",
    example: "0154",
    aliases: ["numero", "dorsal"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.photo",
    label: "Participante - Foto (alias)",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },
  {
    path: "participant.photoUrl",
    label: "Participante - Foto URL",
    valueType: "image",
    required: true,
    example: "",
    aliases: ["foto"],
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "participant",
    groupLabel: "CLICKATÓN — PARTICIPANTE",
  },

  // —— Edición ——
  {
    path: "edition.id",
    label: "Edición - ID",
    valueType: "text",
    example: "ed-rosario-2026",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.name",
    label: "Edición - Nombre",
    valueType: "text",
    required: true,
    example: "Clickatón Rosario",
    aliases: ["edicion"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.shortName",
    label: "Edición - Nombre corto",
    valueType: "text",
    example: "Rosario",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.city",
    label: "Edición - Ciudad",
    valueType: "text",
    example: "Rosario",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.venue",
    label: "Edición - Venue",
    valueType: "text",
    example: "Centro de la ciudad",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.eventDate",
    label: "Edición - Fecha evento",
    valueType: "date",
    required: true,
    example: "2026-09-19",
    formatters: [...DATE_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.eventDateFormatted",
    label: "Edición - Fecha formateada",
    valueType: "text",
    example: "19 DE SEPTIEMBRE",
    aliases: ["fecha"],
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.registrationDate",
    label: "Edición - Fecha inscripción",
    valueType: "date",
    example: "2026-08-01",
    formatters: [...DATE_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.registrationDateFormatted",
    label: "Edición - Fecha inscripción formateada",
    valueType: "text",
    example: "01/08/2026",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.theme",
    label: "Edición - Tema",
    valueType: "text",
    example: "Miradas urbanas",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },
  {
    path: "edition.slug",
    label: "Edición - Slug",
    valueType: "text",
    example: "clickaton-rosario-2026",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "edition",
    groupLabel: "CLICKATÓN — EDICIÓN",
  },

  // —— Evento ——
  {
    path: "event.name",
    label: "Evento - Nombre",
    valueType: "text",
    example: "Clickatón Rosario",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "event",
    groupLabel: "CLICKATÓN — EVENTO",
  },
  {
    path: "event.date",
    label: "Evento - Fecha",
    valueType: "date",
    example: "2026-09-19",
    formatters: [...DATE_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "event",
    groupLabel: "CLICKATÓN — EVENTO",
  },
  {
    path: "event.dateFormatted",
    label: "Evento - Fecha formateada",
    valueType: "text",
    example: "19 DE SEPTIEMBRE",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "event",
    groupLabel: "CLICKATÓN — EVENTO",
  },
  {
    path: "event.city",
    label: "Evento - Ciudad",
    valueType: "text",
    example: "Rosario",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "event",
    groupLabel: "CLICKATÓN — EVENTO",
  },
  {
    path: "event.venue",
    label: "Evento - Venue",
    valueType: "text",
    example: "Centro de la ciudad",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "event",
    groupLabel: "CLICKATÓN — EVENTO",
  },

  // —— Marca ——
  {
    path: "branding.name",
    label: "Marca - Nombre",
    valueType: "text",
    example: "Clickatón",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "Clickatón",
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.logo",
    label: "Marca - Logo (alias)",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.logoUrl",
    label: "Marca - Logo URL",
    valueType: "image",
    example: "",
    aliases: ["logo"],
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.isotype",
    label: "Marca - Isotipo",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.isotypeUrl",
    label: "Marca - Isotipo URL",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.primaryColor",
    label: "Marca - Color primario",
    valueType: "text",
    example: "#FFE600",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "#FFE600",
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.secondaryColor",
    label: "Marca - Color secundario",
    valueType: "text",
    example: "#000000",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "#000000",
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.accentColor",
    label: "Marca - Color acento",
    valueType: "text",
    example: "#3B1F6E",
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: "#3B1F6E",
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.website",
    label: "Marca - Website",
    valueType: "text",
    example: "maratonfotografica.com",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },
  {
    path: "branding.instagram",
    label: "Marca - Instagram",
    valueType: "text",
    example: "@clickaton",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "branding",
    groupLabel: "CLICKATÓN — MARCA",
  },

  // —— Organización ——
  {
    path: "organization.name",
    label: "Organización - Nombre",
    valueType: "text",
    example: "DNX",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "organization",
    groupLabel: "CLICKATÓN — ORGANIZACIÓN",
  },
  {
    path: "organization.logo",
    label: "Organización - Logo",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "organization",
    groupLabel: "CLICKATÓN — ORGANIZACIÓN",
  },
  {
    path: "organization.instagram",
    label: "Organización - Instagram",
    valueType: "text",
    example: "@dnxfotografia",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "organization",
    groupLabel: "CLICKATÓN — ORGANIZACIÓN",
  },

  // —— Sponsors ——
  {
    path: "sponsors.primary.logo",
    label: "Sponsor primario - Logo",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "sponsors",
    groupLabel: "CLICKATÓN — SPONSORS",
  },
  {
    path: "sponsors.primary.name",
    label: "Sponsor primario - Nombre",
    valueType: "text",
    example: "Sponsor Principal",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "sponsors",
    groupLabel: "CLICKATÓN — SPONSORS",
  },
  {
    path: "sponsors.secondary.logo",
    label: "Sponsor secundario - Logo",
    valueType: "image",
    example: "",
    formatters: ["none"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "sponsors",
    groupLabel: "CLICKATÓN — SPONSORS",
  },
  {
    path: "sponsors.secondary.name",
    label: "Sponsor secundario - Nombre",
    valueType: "text",
    example: "Sponsor Secundario",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "sponsors",
    groupLabel: "CLICKATÓN — SPONSORS",
  },

  // —— Placa ——
  {
    path: "card.title",
    label: "Placa - Título",
    valueType: "text",
    example: "¡BIENVENID@ A CLICKATÓN!",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "card",
    groupLabel: "CLICKATÓN — PLACA",
  },
  {
    path: "card.subtitle",
    label: "Placa - Subtítulo",
    valueType: "text",
    example: "SOY PARTE DE CLICKATÓN",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "card",
    groupLabel: "CLICKATÓN — PLACA",
  },
  {
    path: "card.message",
    label: "Placa - Mensaje",
    valueType: "text",
    example:
      "Una comunidad que recorre, crea y muestra la ciudad desde nuevas miradas.",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "card",
    groupLabel: "CLICKATÓN — PLACA",
  },
  {
    path: "card.callToAction",
    label: "Placa - CTA",
    valueType: "text",
    example: "Compartí tu placa",
    formatters: [...TEXT_FMT],
    usableIn: ["TEXT"],
    defaultFallback: "",
    group: "card",
    groupLabel: "CLICKATÓN — PLACA",
  },
];
