export const VISUAL_REFERENCE_VALIDATION_CODES = [
  "VISUAL_REFERENCE_ID_REQUIRED",
  "VISUAL_REFERENCE_DUPLICATE_ID",
  "VISUAL_REFERENCE_TITLE_REQUIRED",
  "VISUAL_REFERENCE_DESCRIPTION_REQUIRED",
  "VISUAL_REFERENCE_NICHE_REQUIRED",
  "VISUAL_REFERENCE_INVALID_NICHE",
  "VISUAL_REFERENCE_IMAGE_PATH_REQUIRED",
  "VISUAL_REFERENCE_IMAGE_NOT_FOUND",
  "VISUAL_REFERENCE_IMAGE_OUTSIDE_ALLOWED_DIRECTORY",
  "VISUAL_REFERENCE_USAGE_NOT_AUTHORIZED",
  "VISUAL_REFERENCE_INTERNAL_REVIEW_NOT_AUTHORIZED",
  "VISUAL_REFERENCE_UNKNOWN_RIGHTS",
  "VISUAL_REFERENCE_ATTRIBUTION_REQUIRED",
  "VISUAL_REFERENCE_ATTRIBUTION_MISSING",
  "VISUAL_REFERENCE_EXPIRED",
  "VISUAL_REFERENCE_PUBLIC_AUTHORIZATION_FORBIDDEN",
  "VISUAL_REFERENCE_UNSUPPORTED_SOURCE",
  "VISUAL_REFERENCE_INVALID_STATUS",
  "VISUAL_REFERENCE_INVALID_ORIENTATION",
  "VISUAL_REFERENCE_INVALID_MIME",
  "VISUAL_REFERENCE_FILE_TOO_LARGE",
  "VISUAL_REFERENCE_EDUCATIONAL_PURPOSE_REQUIRED",
  "VISUAL_REFERENCE_INVALID_EDUCATIONAL_PURPOSE",
  "VISUAL_REFERENCE_PATH_TRAVERSAL",
] as const;

export type VisualReferenceValidationCode =
  (typeof VISUAL_REFERENCE_VALIDATION_CODES)[number];

export type VisualReferenceValidationIssue = {
  code: VisualReferenceValidationCode;
  message: string;
  referenceId?: string;
};
