const lines = [
  "DNX visual references checklist — qué necesitás para cargar una referencia",
  "",
  "Archivos",
  "  • Colocá (vía visual-references:add) un JPEG/PNG/WebP ≤ 10 MB en:",
  "    apps/dnx-sales-assistant/.local/visual-references/assets/",
  "  • Catálogo local (ignorado por Git):",
  "    apps/dnx-sales-assistant/.local/visual-references/catalog.json",
  "",
  "Metadatos obligatorios",
  "  - [ ] id estable (no uses solo el nombre de archivo)",
  "  - [ ] title / description",
  "  - [ ] al menos un nicho del catálogo DNX",
  "  - [ ] propósito educativo (composición, iluminación, etc.)",
  "  - [ ] orientation: LANDSCAPE | PORTRAIT | SQUARE",
  "  - [ ] source.kind = LOCAL_CURATED",
  "",
  "Derechos (obligatorio antes de aprobar)",
  "  - [ ] usageAuthorized = true",
  "  - [ ] authorizedForInternalReview = true",
  "  - [ ] authorizedForPublicAssistant = false (esta etapa)",
  "  - [ ] authorizationBasis ≠ UNKNOWN",
  "  - [ ] authorName cuando corresponda",
  "  - [ ] attributionText si attributionRequired",
  "  - [ ] expiresAt si aplica",
  "",
  "Flujo",
  "  1) pnpm --filter dnx-sales-assistant visual-references:add",
  "  2) Completá derechos en el catálogo local (queda DRAFT)",
  "  3) pnpm --filter dnx-sales-assistant visual-references:approve <id>",
  "  4) pnpm --filter dnx-sales-assistant visual-references:validate",
  "",
  "Ninguna fotografía puede mostrarse sólo por estar disponible técnicamente.",
  "Debe existir autorización explícita y verificable.",
  "Durante esta etapa las referencias sólo están en el laboratorio local.",
];

for (const line of lines) console.log(line);
