export const CALIBRATION_CODES = [
  "CALIBRATION_TOO_FORMAL",
  "CALIBRATION_TOO_ROBOTIC",
  "CALIBRATION_TOO_LONG",
  "CALIBRATION_TOO_SHORT",
  "CALIBRATION_WRONG_QUESTION",
  "CALIBRATION_WRONG_QUESTION_ORDER",
  "CALIBRATION_REPEATED_QUESTION",
  "CALIBRATION_ASKED_KNOWN_FIELD",
  "CALIBRATION_UNNATURAL_CONFIRMATION",
  "CALIBRATION_EXCESSIVE_ENTHUSIASM",
  "CALIBRATION_CONTEXT_LOSS",
  "CALIBRATION_INCORRECT_INTENT",
  "CALIBRATION_INCORRECT_EXTRACTION",
  "CALIBRATION_CORRECTION_NOT_UNDERSTOOD",
  "CALIBRATION_BAD_COPY_VARIANT",
  "CALIBRATION_MISSING_EXPLANATION",
  "CALIBRATION_UNNECESSARY_EXPLANATION",
  "CALIBRATION_VISUAL_NICHE_INCORRECT",
  "CALIBRATION_VISUAL_RESPONSE_INCORRECT",
  "CALIBRATION_HIGH_SCORE_HUMAN_REJECTED",
  "CALIBRATION_LOW_SCORE_HUMAN_APPROVED",
  "CALIBRATION_OTHER",
  "PRICING_EXPLANATION_TOO_TECHNICAL",
  "PRICING_EXPLANATION_TOO_LONG",
  "PRICING_EXPLANATION_UNCLEAR",
  "PRICING_EXPLANATION_MISSING_COMPONENT",
  "PRICING_EXPLANATION_WRONG_ASSUMPTION",
  "PRICING_EXPLANATION_MINIMUM_UNCLEAR",
  "PRICING_EXPLANATION_RECOMMENDED_UNCLEAR",
  "PRICING_EXPLANATION_OTHER",
] as const;

export type CalibrationCode = (typeof CALIBRATION_CODES)[number];

export function isCalibrationCode(value: string): value is CalibrationCode {
  return (CALIBRATION_CODES as readonly string[]).includes(value);
}
