export const FUNNEL_COOKIE_NAME = "cmlf_funnel_vid";

export const FUNNEL_EVENTS = {
  ORDER_CONFIG_VIEW: "ORDER_CONFIG_VIEW",
  ORDER_FINAL_VIEW: "ORDER_FINAL_VIEW",
  PAYMENT_START: "PAYMENT_START",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  ORDER_CREATED: "ORDER_CREATED",
  PAYMENT_REDIRECT_PREPARING_SHOWN: "PAYMENT_REDIRECT_PREPARING_SHOWN",
  PAYMENT_RETRY_CLICKED: "PAYMENT_RETRY_CLICKED",
  PAYMENT_PENDING_STATUS_REFRESHED: "PAYMENT_PENDING_STATUS_REFRESHED",
  PENDING_ORDER_BANNER_SHOWN: "PENDING_ORDER_BANNER_SHOWN",
  PENDING_ORDER_BANNER_CONTINUE_CLICKED: "PENDING_ORDER_BANNER_CONTINUE_CLICKED",
  PENDING_ORDER_BANNER_DISMISSED: "PENDING_ORDER_BANNER_DISMISSED",
  /** Landing /recomendanos y embajadores públicos */
  REFERRAL_LANDING_VIEW: "REFERRAL_LANDING_VIEW",
  REFERRAL_FORM_STARTED: "REFERRAL_FORM_STARTED",
  REFERRAL_FORM_SUBMITTED: "REFERRAL_FORM_SUBMITTED",
  REFERRAL_USER_CREATED: "REFERRAL_USER_CREATED",
  REFERRAL_LINK_GENERATED: "REFERRAL_LINK_GENERATED",
  REFERRAL_COPY_LINK: "REFERRAL_COPY_LINK",
  REFERRAL_COPY_MESSAGE: "REFERRAL_COPY_MESSAGE",
  REFERRAL_WHATSAPP_SHARE_CLICKED: "REFERRAL_WHATSAPP_SHARE_CLICKED",
  REFERRAL_EXISTING_USER_RECOVERED: "REFERRAL_EXISTING_USER_RECOVERED",
} as const;

export type FunnelEventName = (typeof FUNNEL_EVENTS)[keyof typeof FUNNEL_EVENTS];

export const ALLOWED_FUNNEL_EVENTS = new Set<string>(Object.values(FUNNEL_EVENTS));
