export type CommunicationErrorCode =
  | "PROVIDER_NOT_REGISTERED"
  | "PROVIDER_ALREADY_REGISTERED"
  | "PROVIDER_MISMATCH"
  | "PROVIDER_REJECTED"
  | "PROVIDER_AUTHENTICATION_FAILED"
  | "PROVIDER_RATE_LIMITED"
  | "PROVIDER_RESPONSE_INVALID"
  | "CHANNEL_NOT_SUPPORTED"
  | "INVALID_REQUEST"
  | "INVALID_RECIPIENT"
  | "INVALID_TEMPLATE"
  | "INVALID_TEMPLATE_PAYLOAD"
  | "INVALID_EVENT"
  | "TEMPLATE_NOT_FOUND"
  | "TEMPLATE_ALREADY_REGISTERED"
  | "BRAND_NOT_FOUND"
  | "LOCALE_NOT_SUPPORTED"
  | "UNSAFE_URL"
  | "RENDER_NOT_IMPLEMENTED"
  | "PREVIEW_NOT_IMPLEMENTED"
  | "RENDER_FAILED"
  | "PREVIEW_FAILED"
  | "SEND_FAILED"
  | "SCHEDULE_NOT_IMPLEMENTED"
  | "TRIGGER_NOT_IMPLEMENTED"
  | "OPERATION_NOT_SUPPORTED"
  | "DRY_RUN"
  | "CONFIGURATION_ERROR"
  | "RESEND_CONFIGURATION_MISSING"
  | "LIVE_SEND_DISABLED"
  | "LIVE_SEND_CONFIRMATION_REQUIRED"
  | "RECIPIENT_NOT_ALLOWED"
  | "INVALID_ALLOWED_RECIPIENTS"
  | "INVALID_FROM_ADDRESS"
  | "WEBHOOK_DISABLED"
  | "WEBHOOK_PAYLOAD_EMPTY"
  | "WEBHOOK_PAYLOAD_TOO_LARGE"
  | "WEBHOOK_JSON_INVALID"
  | "WEBHOOK_SCHEMA_INVALID"
  | "WEBHOOK_SIGNATURE_MISSING"
  | "WEBHOOK_SIGNATURE_INVALID"
  | "WEBHOOK_SIGNATURE_EXPIRED"
  | "WEBHOOK_EVENT_UNSUPPORTED"
  | "WEBHOOK_EVENT_NOT_ALLOWED_IN_ENVIRONMENT"
  | "WEBHOOK_EVENT_DUPLICATE"
  | "WEBHOOK_HANDLER_FAILED"
  | "WEBHOOK_PROVIDER_EVENT_ID_MISSING"
  | "WEBHOOK_TIMESTAMP_INVALID"
  | "WEBHOOK_CONFIGURATION_MISSING"
  | "WEBHOOK_RATE_LIMITED"
  | "UNKNOWN";

export class CommunicationError extends Error {
  readonly code: CommunicationErrorCode;
  readonly details?: Readonly<Record<string, string | number | boolean | null>>;

  constructor(
    code: CommunicationErrorCode,
    message: string,
    details?: Readonly<Record<string, string | number | boolean | null>>,
  ) {
    super(message);
    this.name = "CommunicationError";
    this.code = code;
    this.details = details;
  }
}
