export const STOP_REASONS = [
  "TASK_COMPLETED",
  "HUMAN_REQUIRED",
  "SAFETY_BLOCK",
  "BUDGET_EXCEEDED",
  "TASK_ITERATION_LIMIT",
  "STAGE_ITERATION_LIMIT",
  "PLANNER_ERROR",
  "CURSOR_ERROR",
  "REVIEWER_ERROR",
  "TIMEOUT",
  "CANCELLED",
  "UNKNOWN_STATE",
  "NO_PROGRESS_DETECTED",
  "WRITE_AUTHORIZATION_REQUIRED",
  "CONCURRENCY_LIMIT_REACHED",
  "FORBIDDEN_AUTOMATIC",
  "DIFF_SIZE_HUMAN_REQUIRED",
  "SCOPE_EXPANSION_HUMAN_REQUIRED",
  "RECOVERY_REQUIRED",
] as const;

export type StopReason = (typeof STOP_REASONS)[number];

export const TERMINAL_TASK_STATUSES = [
  "COMPLETED",
  "HUMAN_REQUIRED",
  "BLOCKED",
  "FAILED",
  "CANCELLED",
] as const;
