import type { ClickatonTemplatePreset } from "./types";
import { layout } from "./layout";

const W = 1080;
const H = 1920;

/**
 * CLICKATON_WELCOME_STORY_V1 — Story 1080×1920
 * ¡BIENVENID@ A CLICKATÓN!
 */
export const CLICKATON_WELCOME_STORY_V1: ClickatonTemplatePreset = {
  presetId: "clickaton-welcome-story-v1",
  name: "Bienvenid@ a Clickatón",
  description: "Placa de bienvenida Instagram Story para participantes.",
  meta: {
    product: "clickaton",
    templateKey: "CLICKATON_WELCOME_STORY_V1",
    templateVersion: 1,
    format: "instagram_story",
    purpose: "participant_welcome",
    status: "published",
    createdAt: "2026-08-01",
    official: true,
  },
  payload: {
    canvas: {
      width: W,
      height: H,
      background: "#000000",
      dpi: 72,
    },
    blocks: [
      {
        id: "welcome-bg",
        type: "BACKGROUND",
        pageIndex: 0,
        name: "Fondo",
        layout: layout(0, 0, W, H, 0, { locked: true }),
        configJson: { backgroundColor: "#000000", src: "", fit: "cover" },
      },
      {
        id: "welcome-accent",
        type: "SHAPE",
        pageIndex: 0,
        name: "Acento amarillo",
        layout: layout(0, 0, W, 28, 1),
        configJson: {
          variant: "rectangle",
          fill: "#FFE600",
          stroke: "#FFE600",
          strokeWidth: 0,
        },
      },
      {
        id: "welcome-title",
        type: "TEXT",
        pageIndex: 0,
        name: "Título",
        layout: layout(64, 80, 952, 160, 10),
        configJson: {
          content: "¡BIENVENID@ A\nCLICKATÓN!",
          fontFamily: "Barlow Condensed",
          fontSize: 72,
          fontWeight: 800,
          lineHeight: 1.05,
          letterSpacing: 1,
          textAlign: "CENTER",
          color: "#FFE600",
        },
      },
      {
        id: "welcome-photo",
        type: "PHOTO",
        pageIndex: 0,
        name: "Foto participante",
        layout: layout(240, 280, 600, 600, 20),
        configJson: {
          src: "",
          fit: "cover",
          maskShape: "circle",
          borderRadius: 0,
          source: { variableKey: "participant.photoUrl" },
        },
      },
      {
        id: "welcome-name",
        type: "VARIABLE_TEXT",
        pageIndex: 0,
        name: "Nombre",
        layout: layout(64, 920, 952, 80, 30),
        configJson: {
          variableKey: "participant.fullName",
          fallback: "—",
          fontFamily: "Barlow Condensed",
          fontSize: 56,
          fontWeight: 700,
          textAlign: "CENTER",
          color: "#FFFFFF",
          lineHeight: 1.1,
        },
      },
      {
        id: "welcome-ig",
        type: "VARIABLE_TEXT",
        pageIndex: 0,
        name: "Instagram",
        layout: layout(64, 1000, 952, 48, 31),
        configJson: {
          variableKey: "participant.instagramHandle",
          fallback: "",
          fontFamily: "DM Sans",
          fontSize: 32,
          fontWeight: 500,
          textAlign: "CENTER",
          color: "#FFE600",
          lineHeight: 1.2,
        },
      },
      {
        id: "welcome-number",
        type: "VARIABLE_TEXT",
        pageIndex: 0,
        name: "Número",
        layout: layout(64, 1080, 952, 56, 32),
        configJson: {
          variableKey: "participant.numberFormatted",
          fallback: "",
          fontFamily: "Barlow Condensed",
          fontSize: 40,
          fontWeight: 700,
          textAlign: "CENTER",
          color: "#FFFFFF",
          lineHeight: 1.1,
        },
      },
      {
        id: "welcome-meta",
        type: "TEXT",
        pageIndex: 0,
        name: "Categoría y ciudad",
        layout: layout(64, 1160, 952, 48, 33),
        configJson: {
          content: "{participant.category} · {participant.city}",
          fontFamily: "DM Sans",
          fontSize: 28,
          fontWeight: 500,
          textAlign: "CENTER",
          color: "#FFFFFF",
          lineHeight: 1.2,
        },
      },
      {
        id: "welcome-message",
        type: "VARIABLE_TEXT",
        pageIndex: 0,
        name: "Mensaje",
        layout: layout(96, 1300, 888, 160, 34),
        configJson: {
          variableKey: "card.message",
          fallback:
            "Una comunidad que recorre,\ncrea y muestra la ciudad\ndesde nuevas miradas.",
          fontFamily: "DM Sans",
          fontSize: 30,
          fontWeight: 400,
          textAlign: "CENTER",
          color: "#FFFFFF",
          lineHeight: 1.4,
        },
      },
      {
        id: "welcome-edition",
        type: "TEXT",
        pageIndex: 0,
        name: "Edición y fecha",
        layout: layout(64, 1680, 952, 80, 40),
        configJson: {
          content: "{edition.name}\n{edition.eventDateFormatted}",
          fontFamily: "DM Sans",
          fontSize: 26,
          fontWeight: 500,
          textAlign: "CENTER",
          color: "#FFFFFF",
          lineHeight: 1.35,
        },
      },
      {
        id: "welcome-logo",
        type: "IMAGE",
        pageIndex: 0,
        name: "Logo Clickatón",
        layout: layout(440, 1780, 200, 80, 41),
        configJson: {
          src: "",
          fit: "contain",
          source: { variableKey: "branding.logoUrl" },
        },
      },
      {
        id: "welcome-violet",
        type: "SHAPE",
        pageIndex: 0,
        name: "Acento violeta",
        layout: layout(0, 1892, W, 28, 2),
        configJson: {
          variant: "rectangle",
          fill: "#3B1F6E",
          stroke: "#3B1F6E",
          strokeWidth: 0,
        },
      },
    ],
    variableBindings: [
      {
        blockId: "welcome-name",
        targetPath: "variableKey",
        variableKey: "participant.fullName",
      },
      {
        blockId: "welcome-ig",
        targetPath: "variableKey",
        variableKey: "participant.instagramHandle",
      },
      {
        blockId: "welcome-number",
        targetPath: "variableKey",
        variableKey: "participant.numberFormatted",
      },
      {
        blockId: "welcome-photo",
        targetPath: "source.variableKey",
        variableKey: "participant.photoUrl",
      },
      {
        blockId: "welcome-message",
        targetPath: "variableKey",
        variableKey: "card.message",
      },
      {
        blockId: "welcome-logo",
        targetPath: "source.variableKey",
        variableKey: "branding.logoUrl",
      },
    ],
    meta: {
      product: "clickaton",
      templateKey: "CLICKATON_WELCOME_STORY_V1",
      templateVersion: 1,
      format: "instagram_story",
      purpose: "participant_welcome",
      templatePageCount: 1,
    },
  },
};
