import type { TemplateVariableDefinition } from "../../variables/types";

/**
 * Variables de FotoRank: lo que lleva un diploma de concurso.
 *
 * Salen de los marcadores que el diploma ya usa hoy en
 * `apps/fotorank/app/lib/fotorank/diplomas/layoutSchema.ts`, no de una lista inventada: el día
 * que los diplomas migren a este editor, las plantillas viejas siguen resolviendo.
 *
 * Las imágenes son las dos que un diploma necesita y que el producto ya tiene: el logo de quien
 * organiza y la obra premiada.
 */
export const FOTORANK_TEMPLATE_VARIABLE_DEFINITIONS: TemplateVariableDefinition[] = [
  {
    path: "recipientName",
    label: "Premiado - Nombre",
    description: "A quién se le entrega el diploma.",
    valueType: "text",
    required: true,
    example: "Lucía Fernández",
    aliases: ["premiado", "ganador", "nombre"],
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "premiado",
    groupLabel: "Premiado",
  },
  {
    path: "entryTitle",
    label: "Premiado - Título de la obra",
    valueType: "text",
    example: "Amanecer en el Paraná",
    formatters: ["none", "uppercase", "titleCase", "truncate"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "premiado",
    groupLabel: "Premiado",
  },
  {
    path: "entryImage",
    label: "Premiado - Obra",
    description: "La fotografía premiada.",
    valueType: "image",
    example: "fotorank/ejemplo/obra.jpg",
    aliases: ["obra", "fotopremiada"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "premiado",
    groupLabel: "Premiado",
  },
  {
    path: "prizeLabel",
    label: "Premio - Distinción",
    description: "Primer premio, mención, finalista.",
    valueType: "text",
    required: true,
    example: "Primer premio",
    aliases: ["premio", "distincion"],
    formatters: ["none", "uppercase"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "premio",
    groupLabel: "Premio",
  },
  {
    path: "categoryName",
    label: "Premio - Categoría",
    valueType: "text",
    example: "Paisaje",
    formatters: ["none", "uppercase", "titleCase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "premio",
    groupLabel: "Premio",
  },
  {
    path: "contestTitle",
    label: "Concurso - Nombre",
    valueType: "text",
    required: true,
    example: "Santa Fe en Foco 2026",
    aliases: ["concurso"],
    formatters: ["none", "uppercase", "titleCase"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "concurso",
    groupLabel: "Concurso",
  },
  {
    path: "organizerName",
    label: "Concurso - Organiza",
    valueType: "text",
    example: "Sociedad de Fotógrafos Profesionales de Rosario",
    aliases: ["organizador"],
    formatters: ["none", "uppercase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "concurso",
    groupLabel: "Concurso",
  },
  {
    path: "organizerLogo",
    label: "Concurso - Logo de quien organiza",
    valueType: "image",
    example: "fotorank/ejemplo/logo.png",
    aliases: ["logoorganizador"],
    usableIn: ["IMAGE"],
    defaultFallback: null,
    group: "concurso",
    groupLabel: "Concurso",
  },
  {
    path: "issuedDate",
    label: "Diploma - Fecha de entrega",
    valueType: "date",
    example: "2026-11-20",
    formatters: ["date.short", "date.long", "date.longUppercase"],
    usableIn: ["TEXT"],
    defaultFallback: "—",
    group: "diploma",
    groupLabel: "Diploma",
  },
  {
    path: "diplomaCode",
    label: "Diploma - Código",
    description: "Identifica a este diploma. Es lo que se verifica.",
    valueType: "text",
    required: true,
    example: "FR-2026-00184",
    aliases: ["codigo"],
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "diploma",
    groupLabel: "Diploma",
  },
  {
    path: "verificationUrl",
    label: "Diploma - URL de verificación",
    description: "La dirección que confirma que el diploma es auténtico. Es lo que va en el QR.",
    valueType: "qrUrl",
    required: true,
    example: "https://fotorank.com/diplomas/verificar/AB12CD34",
    aliases: ["qr", "verificador"],
    formatters: ["none"],
    usableIn: ["TEXT"],
    defaultFallback: null,
    group: "diploma",
    groupLabel: "Diploma",
  },
];
