import type { DiplomaLayoutBlock } from "../layoutSchema";
import {
  bottomSealStripe,
  H,
  medalPlaque,
  ribbonBehind,
  stdDynamicStack,
  topInstitutionalBand,
  W,
} from "./builders";
import { layout, line, qr, rect, txt } from "./helpers";
import type { RawPublicTemplate } from "./publicTemplateTypes";

/** Plantillas adicionales: salón fotográfico, workshops, premios, sellos y composiciones decorativas. */
export const extraPublicTemplateRaws: RawPublicTemplate[] = [
  {
    id: "pub-salon-fotografia-oro",
    name: "Salón fotográfico — oro",
    description: "Sensación de salón nacional: marco rico, jerarquía de premio y obra destacada.",
    styleTags: ["fotografia", "clasico", "premio", "institucional", "ornamental"],
    accentColor: "#b45309",
    backgroundColor: "#fdf8f0",
    keywords: ["salón", "exposición", "festival", "nacional"],
    family: "fotografia",
    layout: stdDynamicStack("sfo", {
      titleY: 96,
      recipientY: 210,
      entryY: 278,
      orgY: 404,
      catY: 344,
      prizeY: 308,
      codeY: 472,
      qrX: 698,
      qrY: 448,
      qrS: 88,
      titleSize: 21,
      recipientSize: 27,
      titleColor: "#1c1917",
      bodyColor: "#57534e",
      accentColor: "#b45309",
      subtitle: "SALÓN / CERTAMEN — OBRA SELECCIONADA",
      frame: "rich",
      fontPreset: "editorial",
    }),
  },
  {
    id: "pub-festival-nocturno",
    name: "Festival nocturno",
    description: "Oscuro cinematográfico con acento ámbar y placa central tipo galardón.",
    styleTags: ["oscuro", "gala", "fotografia", "premio", "premium"],
    accentColor: "#f59e0b",
    backgroundColor: "#09090b",
    keywords: ["festival", "noche", "cine", "premiación"],
    family: "fotografia",
    layout: (() => {
      const p = "ffn";
      const blocks = [
        line(`${p}-glow`, 0, 88, W, 2, "#f59e0b", 2),
        ...ribbonBehind(p, 240, 56, "#f59e0b", 0.12),
        txt(`${p}-star`, W / 2 - 40, 100, 80, 28, "★", {
          fontSize: 22,
          color: "#fbbf24",
          textAlign: "center",
        }),
        ...medalPlaque(p, W / 2, 200, 52, "#f59e0b", "#18181b"),
        txt(`${p}-pr`, 48, 268, W - 96, 36, "{{prizeLabel}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#fbbf24",
          textAlign: "center",
        }),
        txt(`${p}-ct`, 48, 120, W - 96, 36, "{{contestTitle}}", {
          fontSize: 16,
          fontWeight: "bold",
          color: "#e4e4e7",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 320, W - 96, 44, "{{recipientName}}", {
          fontSize: 24,
          fontWeight: "bold",
          color: "#fafafa",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 384, W - 96, 26, "Serie / obra: {{entryTitle}}", {
          fontSize: 11,
          color: "#a1a1aa",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 428, W - 96, 40, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#71717a",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 488, W - 96, 18, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 9,
          color: "#52525b",
          textAlign: "center",
        }),
        qr(`${p}-q`, 688, 420, 92),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-workshop-luz",
    name: "Workshop — luz y encuadre",
    description: "Claro y dinámico para clases, mentorías y talleres fotográficos.",
    styleTags: ["workshop", "moderno", "minimal", "reconocimiento"],
    accentColor: "#0284c7",
    backgroundColor: "#f0f9ff",
    keywords: ["taller", "curso", "seminario", "mentoría"],
    family: "workshop",
    layout: (() => {
      const p = "wwl";
      const blocks = [
        rect(`${p}-accent`, 0, 0, 12, H, { fillColor: "#0284c7", layerName: "Barra" }),
        txt(`${p}-lab`, 48, 56, W - 96, 24, "CONSTANCIA DE PARTICIPACIÓN — WORKSHOP", {
          fontSize: 10,
          fontWeight: "bold",
          color: "#0369a1",
          textAlign: "left",
        }),
        txt(`${p}-t`, 48, 110, W - 96, 40, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#0c4a6e",
          textAlign: "left",
        }),
        txt(`${p}-r`, 48, 200, W - 96, 40, "{{recipientName}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#082f49",
          textAlign: "left",
        }),
        txt(`${p}-e`, 48, 270, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#0e7490",
          textAlign: "left",
        }),
        txt(`${p}-p`, 48, 320, W - 96, 24, "{{prizeLabel}}", {
          fontSize: 11,
          color: "#0284c7",
          textAlign: "left",
        }),
        txt(`${p}-o`, 48, 370, W - 96, 36, "{{organizerName}}\n{{categoryName}}", {
          fontSize: 10,
          color: "#64748b",
          textAlign: "left",
        }),
        txt(`${p}-d`, 48, 450, W - 96, 20, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#94a3b8",
          textAlign: "left",
        }),
        qr(`${p}-q`, 700, 440, 84),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-jurado-honor",
    name: "Jurado — mención de honor",
    description: "Sobrio y amplio para reconocimiento a jurado o comité artístico.",
    styleTags: ["institucional", "corporativo", "reconocimiento", "clasico"],
    accentColor: "#44403c",
    backgroundColor: "#fafaf9",
    keywords: ["jurado", "comité", "honor", "invitado"],
    family: "institucional",
    layout: stdDynamicStack("pjh", {
      titleY: 100,
      recipientY: 210,
      entryY: 278,
      orgY: 408,
      catY: 348,
      prizeY: 312,
      codeY: 470,
      qrX: 702,
      qrY: 452,
      qrS: 86,
      titleSize: 19,
      recipientSize: 24,
      titleColor: "#292524",
      bodyColor: "#78716c",
      accentColor: "#44403c",
      subtitle: "EN RECONOCIMIENTO A LA LABOR DEL JURADO",
      frame: "simple",
      fontPreset: "institutional",
    }),
  },
  {
    id: "pub-serie-documental",
    name: "Mejor serie documental",
    description: "Énfasis en categoría y obra; ideal para reportaje y documental.",
    styleTags: ["fotografia", "editorial", "premio", "artistico"],
    accentColor: "#be123c",
    backgroundColor: "#fff1f2",
    keywords: ["documental", "serie", "reportaje", "ensayo"],
    family: "fotografia",
    layout: (() => {
      const p = "psd";
      const blocks = [
        rect(`${p}-tag`, W - 220, 48, 180, 36, { fillColor: "#be123c", layerName: "Etiqueta" }),
        txt(`${p}-tg`, W - 216, 56, 172, 22, "{{categoryName}}", {
          fontSize: 10,
          fontWeight: "bold",
          color: "#ffffff",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 120, W - 96, 40, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#881337",
          textAlign: "left",
        }),
        txt(`${p}-e`, 48, 200, W - 96, 36, "{{entryTitle}}", {
          fontSize: 18,
          fontWeight: "bold",
          color: "#9f1239",
          textAlign: "left",
        }),
        txt(`${p}-r`, 48, 280, W - 96, 36, "{{recipientName}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#4c0519",
          textAlign: "left",
        }),
        txt(`${p}-p`, 48, 340, W - 96, 28, "{{prizeLabel}}", {
          fontSize: 13,
          fontWeight: "bold",
          color: "#be123c",
          textAlign: "left",
        }),
        txt(`${p}-o`, 48, 400, W - 96, 32, "{{organizerName}}", {
          fontSize: 10,
          color: "#9f1239",
          textAlign: "left",
        }),
        txt(`${p}-d`, 48, 470, W - 96, 20, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#881337",
          textAlign: "left",
        }),
        qr(`${p}-q`, 700, 430, 88),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-mejor-retrato",
    name: "Mejor retrato",
    description: "Composición centrada con marco triple y foco en el galardón.",
    styleTags: ["fotografia", "premio", "clasico", "ornamental"],
    accentColor: "#ca8a04",
    backgroundColor: "#fffbeb",
    keywords: ["retrato", "persona", "estudio"],
    family: "fotografia",
    layout: stdDynamicStack("pmr", {
      titleY: 96,
      recipientY: 214,
      entryY: 282,
      orgY: 404,
      catY: 344,
      prizeY: 308,
      codeY: 472,
      qrX: 700,
      qrY: 450,
      qrS: 90,
      titleSize: 20,
      recipientSize: 28,
      titleColor: "#713f12",
      bodyColor: "#a16207",
      accentColor: "#ca8a04",
      subtitle: "GALARDÓN — CATEGORÍA RETRATO",
      frame: "rich",
      fontPreset: "photo",
    }),
  },
  {
    id: "pub-paisaje-premium",
    name: "Paisaje — mención especial",
    description: "Verdes profundos y filetes finos; evoca naturaleza y aire abierto.",
    styleTags: ["fotografia", "academico", "premio", "azul"],
    accentColor: "#15803d",
    backgroundColor: "#ecfdf5",
    keywords: ["paisaje", "naturaleza", "medio ambiente"],
    family: "fotografia",
    layout: (() => {
      const p = "ppp";
      const blocks = [
        line(`${p}-h`, 48, 96, W - 96, 2, "#15803d", 2),
        txt(`${p}-t`, 48, 120, W - 96, 36, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#14532d",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 180, W - 96, 32, "{{prizeLabel}}", {
          fontSize: 18,
          fontWeight: "bold",
          color: "#15803d",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 240, W - 96, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#052e16",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 310, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#166534",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 370, W - 96, 36, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#15803d",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 460, W - 96, 20, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 9,
          color: "#86efac",
          textAlign: "center",
        }),
        qr(`${p}-q`, 702, 440, 86),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-participacion-calida",
    name: "Participación cálida",
    description: "Amable y clara; constancia de participación sin tono excesivamente formal.",
    styleTags: ["participacion", "beige", "reconocimiento", "minimal"],
    accentColor: "#ea580c",
    backgroundColor: "#fff7ed",
    keywords: ["participación", "constancia", "diploma"],
    family: "participacion",
    layout: stdDynamicStack("ppc", {
      titleY: 102,
      recipientY: 212,
      entryY: 278,
      orgY: 406,
      catY: 346,
      prizeY: 310,
      codeY: 472,
      qrX: 704,
      qrY: 454,
      qrS: 84,
      titleSize: 19,
      recipientSize: 25,
      titleColor: "#7c2d12",
      bodyColor: "#9a3412",
      accentColor: "#ea580c",
      subtitle: "CERTIFICADO DE PARTICIPACIÓN",
      frame: "simple",
      fontPreset: "institutional",
    }),
  },
  {
    id: "pub-premio-publico",
    name: "Premio del público",
    description: "Banda inferior tipo sello y tipografía festiva para votación popular.",
    styleTags: ["premio", "gala", "fotografia", "moderno"],
    accentColor: "#7c3aed",
    backgroundColor: "#faf5ff",
    keywords: ["público", "votación", "popular"],
    family: "premium",
    layout: (() => {
      const p = "ppp2";
      const blocks = [
        txt(`${p}-t`, 48, 100, W - 96, 40, "{{contestTitle}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#5b21b6",
          textAlign: "center",
        }),
        txt(`${p}-badge`, 48, 160, W - 96, 36, "PREMIO DEL PÚBLICO", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#7c3aed",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 230, W - 96, 44, "{{recipientName}}", {
          fontSize: 28,
          fontWeight: "bold",
          color: "#4c1d95",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 310, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#6d28d9",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 370, W - 96, 32, "{{organizerName}} · {{categoryName}}", {
          fontSize: 10,
          color: "#7e22ce",
          textAlign: "center",
        }),
        ...bottomSealStripe(`${p}-seal`, "#ede9fe", "#5b21b6"),
        txt(`${p}-d`, 48, 430, W - 96, 18, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#6b21a8",
          textAlign: "center",
        }),
        qr(`${p}-q`, 696, 360, 90),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-exposicion-colectiva",
    name: "Exposición colectiva",
    description: "Estética galería: mucho blanco, marco fino y título contenido.",
    styleTags: ["artistico", "minimal", "fotografia", "editorial"],
    accentColor: "#0f172a",
    backgroundColor: "#ffffff",
    keywords: ["muestra", "galería", "colectiva"],
    family: "artistico",
    layout: (() => {
      const p = "pec";
      const blocks = [
        rect(`${p}-f`, 36, 36, W - 72, H - 72, {
          fillColor: "transparent",
          strokeColor: "#e2e8f0",
          strokeWidth: 1,
        }),
        rect(`${p}-f2`, 48, 48, W - 96, H - 96, {
          fillColor: "transparent",
          strokeColor: "#cbd5e1",
          strokeWidth: 1,
        }),
        txt(`${p}-k`, 48, 72, W - 96, 20, "EXPOSICIÓN / MUESTRA", {
          fontSize: 9,
          color: "#94a3b8",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 110, W - 96, 36, "{{contestTitle}}", {
          fontSize: 18,
          fontWeight: "bold",
          color: "#0f172a",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 200, W - 96, 40, "{{recipientName}}", {
          fontSize: 24,
          fontWeight: "bold",
          color: "#020617",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 280, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#475569",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 330, W - 96, 24, "{{prizeLabel}}", {
          fontSize: 11,
          color: "#0f172a",
          textAlign: "center",
        }),
        txt(`${p}-o`, 48, 380, W - 96, 28, "{{organizerName}}", {
          fontSize: 10,
          color: "#64748b",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 460, W - 96, 20, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 9,
          color: "#94a3b8",
          textAlign: "center",
        }),
        qr(`${p}-q`, 708, 440, 80),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-cinta-dorada-premio",
    name: "Cinta dorada — primer premio",
    description: "Cinta horizontal y estrella; sensación de medalla sin imagen externa.",
    styleTags: ["premio", "gala", "blanco-dorado", "premium"],
    accentColor: "#d4af37",
    backgroundColor: "#fffef9",
    keywords: ["primero", "oro", "ganador"],
    family: "premium",
    layout: (() => {
      const p = "pcd";
      const blocks = [
        ...ribbonBehind(p, 176, 44, "#d4af37", 0.18),
        txt(`${p}-gl`, W / 2 - 24, 188, 48, 28, "★", {
          fontSize: 24,
          color: "#b45309",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 100, W - 96, 36, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#422006",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 248, W - 96, 40, "{{prizeLabel}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#b45309",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 312, W - 96, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#1c1917",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 384, W - 96, 26, "{{entryTitle}}", {
          fontSize: 12,
          color: "#78716c",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 430, W - 96, 32, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#a8a29e",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 492, W - 96, 18, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#78716c",
          textAlign: "center",
        }),
        qr(`${p}-q`, 698, 448, 86),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-instituto-cultural",
    name: "Instituto cultural",
    description: "Cabecera académica azul y cuerpo ordenado; ideal para entidades culturales.",
    styleTags: ["institucional", "academico", "azul", "clasico"],
    accentColor: "#93c5fd",
    backgroundColor: "#f8fafc",
    keywords: ["museo", "fundación", "cultural"],
    family: "institucional",
    layout: (() => {
      const p = "pic2";
      const blocks = [
        ...topInstitutionalBand(p, 76, "#1e3a8a", "#60a5fa"),
        txt(`${p}-h`, 48, 28, W - 96, 24, "{{organizerName}}", {
          fontSize: 11,
          color: "#e0e7ff",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 120, W - 96, 40, "{{contestTitle}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#1e3a8a",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 210, W - 96, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#172554",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 290, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#334155",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 340, W - 96, 26, "{{prizeLabel}}", {
          fontSize: 12,
          fontWeight: "bold",
          color: "#1d4ed8",
          textAlign: "center",
        }),
        txt(`${p}-c`, 48, 390, W - 96, 22, "{{categoryName}}", {
          fontSize: 11,
          color: "#475569",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 460, W - 96, 20, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 9,
          color: "#64748b",
          textAlign: "center",
        }),
        qr(`${p}-q`, 700, 430, 88),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-burgundy-gala",
    name: "Borgoña — gala",
    description: "Rojo vino y crema; atmósfera de entrega de premios.",
    styleTags: ["gala", "premium", "premio", "clasico"],
    accentColor: "#9f1239",
    backgroundColor: "#fff1f2",
    keywords: ["gala", "velada", "entrega"],
    family: "premium",
    layout: stdDynamicStack("pbg", {
      titleY: 94,
      recipientY: 208,
      entryY: 276,
      orgY: 402,
      catY: 342,
      prizeY: 306,
      codeY: 470,
      qrX: 700,
      qrY: 448,
      qrS: 88,
      titleSize: 21,
      recipientSize: 27,
      titleColor: "#881337",
      bodyColor: "#9f1239",
      accentColor: "#be123c",
      subtitle: "ACTO DE PREMIACIÓN",
      frame: "simple",
      fontPreset: "galaSerif",
    }),
  },
  {
    id: "pub-slate-tech",
    name: "Slate moderno",
    description: "Gris pizarra y acento cian; aspecto contemporáneo y limpio.",
    styleTags: ["moderno", "minimal", "corporativo", "internacional"],
    accentColor: "#06b6d4",
    backgroundColor: "#f1f5f9",
    keywords: ["tech", "actual", "startup"],
    family: "moderno",
    layout: (() => {
      const p = "pst";
      const blocks = [
        rect(`${p}-bar`, W - 200, 0, 200, H, { fillColor: "#0f172a", opacity: 0.06, layerName: "Columna" }),
        line(`${p}-v`, W - 200, 0, 2, H, "#06b6d4", 2),
        txt(`${p}-t`, 48, 100, W - 240, 40, "{{contestTitle}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#0f172a",
          textAlign: "left",
        }),
        txt(`${p}-r`, 48, 200, W - 240, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#020617",
          textAlign: "left",
        }),
        txt(`${p}-e`, 48, 290, W - 240, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#475569",
          textAlign: "left",
        }),
        txt(`${p}-p`, 48, 340, W - 240, 26, "{{prizeLabel}}", {
          fontSize: 12,
          fontWeight: "bold",
          color: "#0891b2",
          textAlign: "left",
        }),
        txt(`${p}-m`, 48, 400, W - 240, 40, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#64748b",
          textAlign: "left",
        }),
        txt(`${p}-d`, 48, 480, W - 240, 20, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#94a3b8",
          textAlign: "left",
        }),
        qr(`${p}-q`, 688, 420, 90),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-copper-vintage",
    name: "Cobre vintage",
    description: "Tonos cobre y marco doble; recuerda papel envejecido elegante.",
    styleTags: ["vintage", "ornamental", "beige", "clasico"],
    accentColor: "#b45309",
    backgroundColor: "#faf6f1",
    keywords: ["retro", "clásico", "sepia"],
    family: "vintage",
    layout: stdDynamicStack("pcv", {
      titleY: 96,
      recipientY: 210,
      entryY: 278,
      orgY: 404,
      catY: 344,
      prizeY: 308,
      codeY: 472,
      qrX: 702,
      qrY: 450,
      qrS: 86,
      titleSize: 20,
      recipientSize: 26,
      titleColor: "#431407",
      bodyColor: "#9a3412",
      accentColor: "#c2410c",
      subtitle: "DIPLOMA CONMEMORATIVO",
      frame: "rich",
      fontPreset: "classicPrint",
    }),
  },
  {
    id: "pub-noche-estrellas",
    name: "Noche estrellada",
    description: "Oscuro con puntos de luz (cuadrados mínimos) y acento dorado.",
    styleTags: ["oscuro", "gala", "artistico", "fotografia"],
    accentColor: "#fcd34d",
    backgroundColor: "#030712",
    keywords: ["noche", "astro", "luz"],
    family: "artistico",
    layout: (() => {
      const p = "pne2";
      const dots: ReturnType<typeof rect>[] = [];
      const positions = [
        [80, 60],
        [720, 80],
        [200, 50],
        [600, 120],
        [400, 70],
      ] as const;
      let i = 0;
      for (const [x, y] of positions) {
        dots.push(rect(`${p}-d${i++}`, x, y, 3, 3, { fillColor: "#fef9c3", opacity: 0.7 }));
      }
      const blocks = [
        ...dots,
        txt(`${p}-t`, 48, 120, W - 96, 40, "{{contestTitle}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#e2e8f0",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 210, W - 96, 48, "{{recipientName}}", {
          fontSize: 30,
          fontWeight: "bold",
          color: "#fef3c7",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 300, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#94a3b8",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 350, W - 96, 28, "{{prizeLabel}}", {
          fontSize: 13,
          fontWeight: "bold",
          color: "#fcd34d",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 410, W - 96, 32, "{{organizerName}} · {{categoryName}}", {
          fontSize: 10,
          color: "#64748b",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 480, W - 96, 18, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 9,
          color: "#475569",
          textAlign: "center",
        }),
        qr(`${p}-q`, 690, 420, 94),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-filmstrip",
    name: "Filmstrip — clásico",
    description: "Franjas horizontales que evocan celuloide; homenaje al medio fotográfico.",
    styleTags: ["fotografia", "vintage", "artistico", "horizontal"],
    accentColor: "#171717",
    backgroundColor: "#fafafa",
    keywords: ["película", "analógico", "celuloide"],
    family: "fotografia",
    layout: (() => {
      const p = "pfs";
      const strips: DiplomaLayoutBlock[] = [];
      for (let i = 0; i < 5; i++) {
        strips.push(rect(`${p}-s${i}`, 48 + i * 140, 52, 120, 28, { fillColor: "#171717", opacity: 0.85 }));
      }
      const blocks = [
        ...strips,
        txt(`${p}-lab`, 48, 100, W - 96, 20, "FOTOGRAFÍA — CERTIFICADO DE MÉRITO", {
          fontSize: 9,
          color: "#525252",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 140, W - 96, 36, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#171717",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 220, W - 96, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#0a0a0a",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 300, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#404040",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 350, W - 96, 26, "{{prizeLabel}}", {
          fontSize: 12,
          fontWeight: "bold",
          color: "#171717",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 400, W - 96, 32, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#737373",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 470, W - 96, 20, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#a3a3a3",
          textAlign: "center",
        }),
        qr(`${p}-q`, 702, 430, 86),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-ice-blue",
    name: "Azul hielo",
    description: "Frío y premium; buen contraste para texto oscuro.",
    styleTags: ["minimal", "internacional", "academico", "azul"],
    accentColor: "#0369a1",
    backgroundColor: "#f0f9ff",
    keywords: ["frío", "nórdico", "limpido"],
    family: "minimal",
    layout: stdDynamicStack("pib", {
      titleY: 98,
      recipientY: 212,
      entryY: 280,
      orgY: 406,
      catY: 346,
      prizeY: 310,
      codeY: 474,
      qrX: 704,
      qrY: 452,
      qrS: 84,
      titleSize: 20,
      recipientSize: 26,
      titleColor: "#0c4a6e",
      bodyColor: "#0369a1",
      accentColor: "#0284c7",
      subtitle: "CERTIFICADO DE LOGRO",
      frame: "simple",
      fontPreset: "minimal",
    }),
  },
  {
    id: "pub-sand-warm",
    name: "Arena cálida",
    description: "Neutro cálido con doble marco suave; versátil para cualquier premio.",
    styleTags: ["beige", "neutro", "clasico", "participacion"],
    accentColor: "#a16207",
    backgroundColor: "#faf8f5",
    keywords: ["neutro", "versátil", "suave"],
    family: "clasico",
    layout: stdDynamicStack("psw", {
      titleY: 94,
      recipientY: 208,
      entryY: 276,
      orgY: 402,
      catY: 342,
      prizeY: 306,
      codeY: 470,
      qrX: 700,
      qrY: 448,
      qrS: 88,
      titleSize: 20,
      recipientSize: 26,
      titleColor: "#422006",
      bodyColor: "#78716c",
      accentColor: "#a16207",
      subtitle: "RECONOCIMIENTO",
      frame: "rich",
      fontPreset: "classicPrint",
    }),
  },
  {
    id: "pub-charcoal-gold",
    name: "Carbón y oro",
    description: "Gris carbón con filetes dorados; look editorial premium.",
    styleTags: ["premium", "negro-dorado", "editorial", "gala"],
    accentColor: "#d4af37",
    backgroundColor: "#1c1917",
    keywords: ["luxury", "editorial", "revista"],
    family: "premium",
    layout: (() => {
      const p = "pcg";
      const blocks = [
        line(`${p}-t`, 48, 72, W - 96, 1, "#d4af37", 1),
        line(`${p}-b`, 48, H - 72, W - 96, 1, "#d4af37", 1),
        txt(`${p}-ct`, 48, 120, W - 96, 40, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#e7e5e4",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 210, W - 96, 48, "{{recipientName}}", {
          fontSize: 28,
          fontWeight: "bold",
          color: "#fafaf9",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 300, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#a8a29e",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 350, W - 96, 28, "{{prizeLabel}}", {
          fontSize: 13,
          fontWeight: "bold",
          color: "#d4af37",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 410, W - 96, 32, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#a8a29e",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 480, W - 96, 18, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#78716c",
          textAlign: "center",
        }),
        qr(`${p}-q`, 696, 420, 92),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-diagonal-blocks",
    name: "Bloques modernos",
    description: "Franjas escalonadas y tipografía firme; estética museo contemporáneo.",
    styleTags: ["artistico", "moderno", "editorial"],
    accentColor: "#ea580c",
    backgroundColor: "#fff7ed",
    keywords: ["bloques", "geométrico", "museo"],
    family: "artistico",
    layout: (() => {
      const p = "pdb";
      const blocks = [
        rect(`${p}-b1`, 0, 140, 280, 24, { fillColor: "#fed7aa", opacity: 0.9 }),
        rect(`${p}-b2`, 120, 180, 280, 24, { fillColor: "#fdba74", opacity: 0.85 }),
        rect(`${p}-b3`, 240, 220, 280, 24, { fillColor: "#fb923c", opacity: 0.75 }),
        txt(`${p}-t`, 48, 100, W - 96, 36, "{{contestTitle}}", {
          fontSize: 22,
          fontWeight: "bold",
          color: "#9a3412",
          textAlign: "left",
        }),
        txt(`${p}-r`, 48, 280, W - 96, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#7c2d12",
          textAlign: "left",
        }),
        txt(`${p}-e`, 48, 360, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#c2410c",
          textAlign: "left",
        }),
        txt(`${p}-p`, 48, 410, W - 96, 26, "{{prizeLabel}}", {
          fontSize: 12,
          fontWeight: "bold",
          color: "#ea580c",
          textAlign: "left",
        }),
        txt(`${p}-m`, 48, 460, W - 96, 36, "{{organizerName}}\n{{categoryName}}", {
          fontSize: 10,
          color: "#9a3412",
          textAlign: "left",
        }),
        txt(`${p}-d`, 48, 520, W - 96, 20, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 8,
          color: "#78716c",
          textAlign: "left",
        }),
        qr(`${p}-q`, 700, 400, 80),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-seleccion-oficial",
    name: "Selección oficial",
    description: "Sello textual y marco triple; para obras admitidas a muestra.",
    styleTags: ["fotografia", "institucional", "clasico", "reconocimiento"],
    accentColor: "#0f766e",
    backgroundColor: "#f0fdfa",
    keywords: ["selección", "oficial", "admitida"],
    family: "fotografia",
    layout: stdDynamicStack("pso", {
      titleY: 108,
      recipientY: 216,
      entryY: 282,
      orgY: 408,
      catY: 348,
      prizeY: 312,
      codeY: 474,
      qrX: 702,
      qrY: 450,
      qrS: 86,
      titleSize: 19,
      recipientSize: 25,
      titleColor: "#134e4a",
      bodyColor: "#115e59",
      accentColor: "#0d9488",
      subtitle: "SELECCIÓN OFICIAL — MUESTRA",
      frame: "rich",
      fontPreset: "photo",
    }),
  },
  {
    id: "pub-masterclass",
    name: "Masterclass fotográfica",
    description: "Dinámica y clara; constancia de asistencia a masterclass o webinar.",
    styleTags: ["workshop", "moderno", "reconocimiento", "minimal"],
    accentColor: "#7c3aed",
    backgroundColor: "#faf5ff",
    keywords: ["masterclass", "webinar", "asistencia"],
    family: "workshop",
    layout: (() => {
      const p = "pma";
      const blocks = [
        rect(`${p}-top`, 0, 0, W, 52, { fillColor: "#7c3aed", opacity: 0.12 }),
        txt(`${p}-k`, 48, 18, W - 96, 22, "MASTERCLASS / FORMACIÓN", {
          fontSize: 10,
          fontWeight: "bold",
          color: "#6d28d9",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 90, W - 96, 36, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#5b21b6",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 180, W - 96, 40, "{{recipientName}}", {
          fontSize: 24,
          fontWeight: "bold",
          color: "#4c1d95",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 260, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#7c3aed",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 320, W - 96, 24, "{{prizeLabel}}", {
          fontSize: 11,
          color: "#6d28d9",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 380, W - 96, 32, "{{organizerName}}\n{{categoryName}}", {
          fontSize: 10,
          color: "#9333ea",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 460, W - 96, 20, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#a78bfa",
          textAlign: "center",
        }),
        qr(`${p}-q`, 706, 420, 82),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-terracota",
    name: "Terracota artística",
    description: "Paleta cálida mediterránea con marco simple.",
    styleTags: ["artistico", "vintage", "beige"],
    accentColor: "#c2410c",
    backgroundColor: "#fff7ed",
    keywords: ["terracota", "mediterráneo", "arte"],
    family: "artistico",
    layout: stdDynamicStack("ptc", {
      titleY: 96,
      recipientY: 210,
      entryY: 278,
      orgY: 404,
      catY: 344,
      prizeY: 308,
      codeY: 472,
      qrX: 700,
      qrY: 448,
      qrS: 86,
      titleSize: 20,
      recipientSize: 26,
      titleColor: "#7c2d12",
      bodyColor: "#9a3412",
      accentColor: "#ea580c",
      subtitle: "CERTIFICADO ARTÍSTICO",
      frame: "simple",
      fontPreset: "editorial",
    }),
  },
  {
    id: "pub-forest-green",
    name: "Verde bosque",
    description: "Verde oscuro y crema; sensación orgánica y premio sostenible.",
    styleTags: ["academico", "institucional", "minimal"],
    accentColor: "#166534",
    backgroundColor: "#f7fee7",
    keywords: ["naturaleza", "eco", "sostenible"],
    family: "institucional",
    layout: stdDynamicStack("pfg", {
      titleY: 100,
      recipientY: 212,
      entryY: 280,
      orgY: 406,
      catY: 346,
      prizeY: 310,
      codeY: 474,
      qrX: 704,
      qrY: 452,
      qrS: 84,
      titleSize: 19,
      recipientSize: 25,
      titleColor: "#14532d",
      bodyColor: "#365314",
      accentColor: "#15803d",
      subtitle: "RECONOCIMIENTO",
      frame: "default",
      fontPreset: "institutional",
    }),
  },
  {
    id: "pub-ocean-deep",
    name: "Océano profundo",
    description: "Azul marino con acento turquesa; ideal para certámenes costeros o viajes.",
    styleTags: ["azul", "moderno", "fotografia", "internacional"],
    accentColor: "#22d3ee",
    backgroundColor: "#0c4a6e",
    keywords: ["mar", "océano", "viaje"],
    family: "fotografia",
    layout: (() => {
      const p = "pod";
      const blocks = [
        line(`${p}-w`, 0, 100, W, 2, "#22d3ee", 2),
        txt(`${p}-t`, 48, 130, W - 96, 40, "{{contestTitle}}", {
          fontSize: 24,
          fontWeight: "bold",
          color: "#e0f2fe",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 220, W - 96, 48, "{{recipientName}}", {
          fontSize: 28,
          fontWeight: "bold",
          color: "#ffffff",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 310, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#bae6fd",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 360, W - 96, 28, "{{prizeLabel}}", {
          fontSize: 13,
          fontWeight: "bold",
          color: "#22d3ee",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 420, W - 96, 32, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#7dd3fc",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 490, W - 96, 18, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#38bdf8",
          textAlign: "center",
        }),
        qr(`${p}-q`, 688, 400, 92),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-minimal-jp",
    name: "Minimal zen",
    description: "Mucho espacio en blanco y una sola línea de acento.",
    styleTags: ["minimal", "neutro", "internacional", "moderno"],
    accentColor: "#171717",
    backgroundColor: "#ffffff",
    keywords: ["zen", "aire", "simple"],
    family: "minimal",
    layout: (() => {
      const p = "pmj";
      const blocks = [
        line(`${p}-l`, 120, 200, W - 240, 1, "#e5e5e5", 1),
        txt(`${p}-t`, 48, 120, W - 96, 32, "{{contestTitle}}", {
          fontSize: 16,
          fontWeight: "bold",
          color: "#171717",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 240, W - 96, 48, "{{recipientName}}", {
          fontSize: 32,
          fontWeight: "bold",
          color: "#0a0a0a",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 340, W - 96, 24, "{{entryTitle}}", {
          fontSize: 11,
          color: "#737373",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 390, W - 96, 22, "{{prizeLabel}}", {
          fontSize: 10,
          color: "#171717",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 440, W - 96, 28, "{{organizerName}} · {{categoryName}}", {
          fontSize: 9,
          color: "#a3a3a3",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 500, W - 96, 16, "{{diplomaCode}} · {{issuedDate}}", {
          fontSize: 8,
          color: "#d4d4d4",
          textAlign: "center",
        }),
        qr(`${p}-q`, 712, 460, 72),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-concurso-oficial",
    name: "Concurso oficial",
    description: "Aspecto de documento oficial con banda superior negra.",
    styleTags: ["institucional", "corporativo", "clasico", "fotografia"],
    accentColor: "#facc15",
    backgroundColor: "#fafafa",
    keywords: ["oficial", "concurso", "reglamento"],
    family: "institucional",
    layout: (() => {
      const p = "pco2";
      const blocks = [
        rect(`${p}-blk`, 0, 0, W, 56, { fillColor: "#171717" }),
        txt(`${p}-h`, 48, 20, W - 96, 22, "CONCURSO OFICIAL DE FOTOGRAFÍA", {
          fontSize: 10,
          fontWeight: "bold",
          color: "#fafafa",
          textAlign: "center",
        }),
        txt(`${p}-t`, 48, 100, W - 96, 36, "{{contestTitle}}", {
          fontSize: 20,
          fontWeight: "bold",
          color: "#171717",
          textAlign: "center",
        }),
        txt(`${p}-r`, 48, 190, W - 96, 44, "{{recipientName}}", {
          fontSize: 26,
          fontWeight: "bold",
          color: "#0a0a0a",
          textAlign: "center",
        }),
        txt(`${p}-e`, 48, 280, W - 96, 28, "{{entryTitle}}", {
          fontSize: 12,
          color: "#525252",
          textAlign: "center",
        }),
        txt(`${p}-p`, 48, 330, W - 96, 26, "{{prizeLabel}}", {
          fontSize: 12,
          fontWeight: "bold",
          color: "#ca8a04",
          textAlign: "center",
        }),
        txt(`${p}-m`, 48, 390, W - 96, 32, "{{categoryName}}\n{{organizerName}}", {
          fontSize: 10,
          color: "#737373",
          textAlign: "center",
        }),
        txt(`${p}-d`, 48, 470, W - 96, 20, "{{diplomaCode}} · {{issuedDate}} · {{verificationUrl}}", {
          fontSize: 8,
          color: "#a3a3a3",
          textAlign: "center",
        }),
        qr(`${p}-q`, 700, 430, 86),
      ];
      return layout(blocks);
    })(),
  },
  {
    id: "pub-honorable-mention",
    name: "Mención honorable",
    description: "Énfasis en la mención; composición clásica simétrica.",
    styleTags: ["reconocimiento", "clasico", "premio", "beige"],
    accentColor: "#854d0e",
    backgroundColor: "#fefce8",
    keywords: ["mención", "honor", "diploma"],
    family: "clasico",
    layout: stdDynamicStack("phm", {
      titleY: 92,
      recipientY: 218,
      entryY: 284,
      orgY: 406,
      catY: 346,
      prizeY: 310,
      codeY: 472,
      qrX: 702,
      qrY: 450,
      qrS: 88,
      titleSize: 18,
      recipientSize: 26,
      titleColor: "#422006",
      bodyColor: "#713f12",
      accentColor: "#a16207",
      subtitle: "MENCIÓN HONORABLE",
      frame: "rich",
      fontPreset: "classicPrint",
    }),
  },
  {
    id: "pub-luxe-rose",
    name: "Rosa luxe",
    description: "Paleta rosa polvo y bronce; distinguida y suave.",
    styleTags: ["premium", "artistico", "gala", "moderno"],
    accentColor: "#be185d",
    backgroundColor: "#fdf2f8",
    keywords: ["rosa", "elegante", "femenino"],
    family: "premium",
    layout: stdDynamicStack("plr", {
      titleY: 96,
      recipientY: 210,
      entryY: 278,
      orgY: 404,
      catY: 344,
      prizeY: 308,
      codeY: 472,
      qrX: 700,
      qrY: 448,
      qrS: 86,
      titleSize: 20,
      recipientSize: 26,
      titleColor: "#831843",
      bodyColor: "#9d174d",
      accentColor: "#be185d",
      subtitle: "DISTINCIÓN ESPECIAL",
      frame: "simple",
      fontPreset: "galaSerif",
    }),
  },
  {
    id: "pub-trayectoria",
    name: "Trayectoria fotográfica",
    description: "Para reconocimientos de carrera o aporte al medio.",
    styleTags: ["reconocimiento", "institucional", "clasico", "fotografia"],
    accentColor: "#57534e",
    backgroundColor: "#fafaf9",
    keywords: ["trayectoria", "carrera", "legado"],
    family: "institucional",
    layout: stdDynamicStack("ptr", {
      titleY: 100,
      recipientY: 212,
      entryY: 278,
      orgY: 406,
      catY: 346,
      prizeY: 310,
      codeY: 474,
      qrX: 704,
      qrY: 452,
      qrS: 84,
      titleSize: 18,
      recipientSize: 26,
      titleColor: "#292524",
      bodyColor: "#57534e",
      accentColor: "#78716c",
      subtitle: "RECONOCIMIENTO A LA TRAYECTORIA",
      frame: "rich",
      fontPreset: "institutional",
    }),
  },
];
